env: "local" # local, dev or prod

bot:
  token: "telegram-token"
  messages_path: "./messages/messages.yaml"

notifications:
  poll_interval: 1s
  upcoming_in: 1h

ollama:
  host: "http://ollama"
  port: "11434"
  model: "model-name" # ollama pull model-name before

postgres:
  host: "postgres"
  port: "5432"
  user: "kypidbot"
  name: "kypidbot"
  password: "kypidbot"
  sslmode: "disable"
